
"""No driver speaks another driver's dialect.

Wave 6b, decision W6b-2. Review §33.

The fault this guards against is specific and has bitten this project
before: an instrument sent a command from the wrong dialect usually does
not error usefully. It logs the complaint in a queue nobody read, ignores
the command, and **leaves the previous setting in force**. The run then
proceeds against whatever the instrument was already doing - which is
often the reset default - and produces numbers that look entirely
ordinary.

The realistic route in is copy-paste. Two TSP drivers sit next to each
other in the tree; so do four SCPI ones. A line lifted from the wrong
neighbour is invisible on review, passes every test that checks a
command is *present*, and only shows up as a measurement that is quietly
wrong.

So this file checks the other half: not that the right commands went
out, but that no foreign ones did.

Traffic is generated by running the checkup against each driver's own
fake transport, which walks every contract method - the same `CASES`
table `test_checkup_all_drivers.py` uses, so a driver added later is
covered without anyone remembering to add it here.
"""
import re

import pytest
from test_checkup_all_drivers import CASES

from core.checkup import Checkup

#: Commands every instrument in the fleet accepts regardless of dialect.
#: TSP instruments accept the IEEE-488.2 common commands too, so these
#: cannot be treated as SCPI-only or the TSP drivers would fail on
#: `*RST` alone.
COMMON = re.compile(r"^\*[A-Z]+", re.IGNORECASE)

#: SCPI mnemonics, matched at the START of a command.
#:
#: Not as substrings, which was the first attempt and was wrong: TSP's
#: `smua.source.func` contains "sour", so a substring rule flagged every
#: TSP driver as speaking SCPI. Anchoring at the start separates them
#: cleanly, because a SCPI command lifted into a TSP driver arrives as
#: its own header while TSP's own paths always begin `smua.`, `print(`
#: or `format.`.
#:
#: The optional leading colon is not cosmetic: the B2901A sends
#: `:SOUR:VOLT` and the GSM-20H10 and U2722A send `SOUR:VOLT`. Both are
#: valid SCPI and both are in use here.
SCPI_HEADER = re.compile(
    r"^:?(SOUR|SENS|OUTP|MEAS|READ|SYST|CONF|FORM|TRIG|INIT|FETC|ABOR|"
    r"TRAC|DISP|STAT|CURR|VOLT|FUNC|ARM|CALC|ROUT)\b",
    re.IGNORECASE)

#: TSP paths. Distinctive enough that a substring match is safe - none
#: of these can appear in a legitimate SCPI command.
TSP_TOKENS = ("smua.", "smub.", "smu.source", "smu.measure", "smu.reset",
              "print(", "printnumber(", "format.asciiprecision",
              "format.data", "localnode.", "errorqueue.", "node[")


def is_scpi(text):
    return bool(SCPI_HEADER.match(text.strip()))


def is_tsp(text):
    lowered = text.lower()
    return any(token in lowered for token in TSP_TOKENS)


#: family -> (does this look like our dialect, does it look foreign)
DIALECTS = {
    "tsp": (is_tsp, is_scpi),
    "scpi": (is_scpi, is_tsp),
}

#: Which family each driver belongs to. Listed explicitly rather than
#: inferred from the class, because "which dialect is this" is exactly
#: the judgement the test exists to pin down - inferring it from the
#: commands would make the check circular.
FAMILY = {
    "Keithley2450": "scpi",
    "Keithley2401": "scpi",
    "Keithley2611A": "tsp",
    "Keithley2635B": "tsp",
    "GWInstekGSM20H10": "scpi",
    "KeysightU2722A": "scpi",
    "KeysightB2901A": "scpi",
    # Driven through the vendor's Python library rather than a text
    # protocol, so there is no dialect to keep clean. Named here rather
    # than omitted, so the coverage check below still sees it.
    "UndalogicMiniSMU": None,
    "DummySMU": None,
}


def commands_sent(driver_cls, transport_factory):
    """Every text this driver put on the wire during a full checkup."""
    transport = transport_factory()
    if not getattr(transport, "connected", False):
        transport.connect("fake")
    driver = driver_cls(transport)
    Checkup(driver, open_circuit=False).run()
    return list(getattr(transport, "sent", []))


def test_every_driver_has_a_declared_dialect(check):
    """Coverage, so a new driver cannot quietly opt out.

    Without this, adding a driver and forgetting to classify it would
    make the checks below silently skip it - a test that passes because
    it examined nothing.
    """
    missing = [name for name, _, _ in CASES if name not in FAMILY]
    check("every driver in CASES has a dialect declared", not missing,
          ", ".join(missing))


@pytest.mark.parametrize("name,driver_cls,transport_factory", CASES,
                         ids=[c[0] for c in CASES])
def test_no_driver_speaks_a_foreign_dialect(check, name, driver_cls,
                                            transport_factory):
    family = FAMILY.get(name)
    if family is None:
        pytest.skip(f"{name} does not use a text dialect")

    sent = commands_sent(driver_cls, transport_factory)
    check(f"{name}: the checkup produced traffic to inspect",
          len(sent) > 5, f"only {len(sent)} commands")

    _, looks_foreign = DIALECTS[family]
    offences = [t for t in sent
                if not COMMON.match(t.strip()) and looks_foreign(t)]

    check(f"{name}: no command carries another dialect",
          not offences, "; ".join(repr(o) for o in offences[:4]))


@pytest.mark.parametrize("name,driver_cls,transport_factory", CASES,
                         ids=[c[0] for c in CASES])
def test_each_driver_actually_speaks_its_own_dialect(check, name, driver_cls,
                                                     transport_factory):
    """The control for the check above.

    A driver that sent nothing recognisable would pass the foreign-token
    test trivially - and so would one whose fake transport silently
    stopped recording. Requiring its own dialect to be present is what
    makes the absence of the others mean something.
    """
    family = FAMILY.get(name)
    if family is None:
        pytest.skip(f"{name} does not use a text dialect")

    sent = commands_sent(driver_cls, transport_factory)
    looks_native, _ = DIALECTS[family]
    hits = [t for t in sent if looks_native(t)]
    check(f"{name}: speaks {family} - {len(hits)} of {len(sent)} commands",
          len(hits) > 0,
          "nothing recognisable as this dialect was sent")
