#!/usr/bin/env python
"""Generate the derived documentation pages.

Why this exists
---------------
Four claims in the old documents rotted silently because a human had to
remember to update them: how many drivers there are, what each one's
envelope is, which have met hardware, and which deviations exist. Each
was true when written. None announced itself when it stopped being true
- `HANDOFF.md` said "five hand-written drivers" while the registry held
nine, and "every driver except the 2450's has been run against its
instrument" thirty-six hours after Wave 6 modified all nine.

So the derived pages are not written. They are computed from the two
things that cannot drift from the code: the driver classes themselves,
and git history.

    drivers/*.py  LIMITS + capability declarations
          |
          +--> instrument note frontmatter (generated block)
          |          |
          |          +--> bench/choosing-an-smu.md      capability matrix
          |          +--> docs/open/checkup-owed.md     verification status
          |
    git log -1 -- <driver>, <base_smu.py>
          |
          +--> "has this driver changed since its last checkup?"

Usage
-----
    uv run python tools/build_docs.py            # write the generated files
    uv run python tools/build_docs.py --check    # fail if they are stale

`--check` is what `tests/test_docs.py` runs. A generated file that has
been hand-edited fails the suite, which is the same mechanism the golden
files use for the maths.

What is NOT generated
---------------------
Judgement. `bench/choosing-an-smu.md` carries a hand-written guidance
section between two markers, and this tool preserves whatever is between
them. Numbers are computed; "use the 2635B for high-resistance samples"
is a person's opinion and stays one.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DOCS = ROOT / "docs"
BENCH = ROOT / "bench"
INSTRUMENTS = DOCS / "instruments"

#: Every driver's verification depends on more than its own file. A
#: change to the shared base class changes the software sweep, the
#: sentinel handling and `apply_ranges()` for every driver that inherits
#: them, so a checkup taken before that change no longer covers them.
#:
#: Deliberately conservative: this over-reports (a docstring edit to
#: base_smu.py marks the whole fleet stale) and never under-reports. A
#: checkup costs three minutes; a driver wrongly believed current costs
#: a dataset. If the over-reporting ever bites, the escape hatch is
#: `bench_revalidated` in the note's frontmatter, which requires a
#: written reason - see docs/reference/schema.md.
SHARED_DEPENDENCIES = ["drivers/base_smu.py"]

GEN_BEGIN = "# --- generated from code by tools/build_docs.py: do not hand-edit"
GEN_END = "# --- end generated ---"

KEEP_BEGIN = "<!-- keep:begin -->"
KEEP_END = "<!-- keep:end -->"

BANNER = (
    "<!-- GENERATED by tools/build_docs.py - do not edit this file.\n"
    "     Edit the instrument notes in docs/instruments/ instead, then\n"
    "     run: uv run python tools/build_docs.py -->\n"
)


# --------------------------------------------------------------------------
# A very small frontmatter reader/writer
#
# Deliberately not PyYAML. Adding a dependency to parse four kinds of
# scalar would put a third-party parser between the documentation and
# the test that guards it, and `uv.lock` is checked with --locked in CI.
# The subset here is stated in docs/reference/schema.md and the schema
# test refuses anything outside it, so the parser cannot silently
# mis-read a construct it does not support: it raises instead.
# --------------------------------------------------------------------------

class FrontmatterError(ValueError):
    """A note's frontmatter is missing, malformed, or uses unsupported YAML."""


def _scalar(text: str):
    """Parse one scalar. Returns str, bool, int, float or None."""
    text = text.strip()
    if text in ("null", "~", ""):
        return None
    if text == "true":
        return True
    if text == "false":
        return False
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'":
        return text[1:-1]
    if text.startswith("[") and text.endswith("]"):
        inner = text[1:-1].strip()
        if not inner:
            return []
        return [_scalar(p) for p in inner.split(",")]
    try:
        return int(text)
    except ValueError:
        pass
    try:
        return float(text)
    except ValueError:
        pass
    if any(ch in text for ch in "{}&*!|>%@`"):
        raise FrontmatterError(
            f"unsupported YAML construct in frontmatter: {text!r}. "
            "The supported subset is in docs/reference/schema.md."
        )
    return text


def read_frontmatter(path: Path) -> tuple[dict, str]:
    """Split a note into (frontmatter dict, body). Raises if absent."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise FrontmatterError(f"{path.relative_to(ROOT)} has no frontmatter block")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise FrontmatterError(f"{path.relative_to(ROOT)} frontmatter is not closed")
    block, body = text[4:end], text[end + 5:]

    data: dict = {}
    key = None
    for raw in block.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if raw.startswith((" ", "\t")) and raw.lstrip().startswith("- "):
            if key is None:
                raise FrontmatterError(f"{path.name}: list item before any key")
            data.setdefault(key, [])
            if not isinstance(data[key], list):
                raise FrontmatterError(f"{path.name}: '{key}' is both scalar and list")
            data[key].append(_scalar(raw.lstrip()[2:]))
            continue
        if ":" not in raw:
            raise FrontmatterError(f"{path.name}: cannot parse line {raw!r}")
        key, _, value = raw.partition(":")
        key = key.strip()
        data[key] = [] if not value.strip() else _scalar(value)
    return data, body


def _dump_scalar(value) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, (int, float)):
        return f"{value:g}"
    text = str(value)
    if text != text.strip() or ":" in text or text.startswith(("[", "-", "#")):
        return f'"{text}"'
    return text


# --------------------------------------------------------------------------
# Facts from the code
# --------------------------------------------------------------------------

def driver_facts() -> dict[str, dict]:
    """Capability facts for every registered driver, keyed by class name.

    Read from the classes rather than from a list here, so a driver
    added to `KNOWN_DRIVERS` appears without anyone remembering.
    """
    from drivers.base_smu import BaseSMU
    from drivers.registry import KNOWN_DRIVERS

    facts = {}
    for cls in KNOWN_DRIVERS:
        limits = cls.LIMITS
        nplc = getattr(cls, "NPLC_RANGE", None)
        module = sys.modules[cls.__module__]
        facts[cls.__name__] = {
            "driver": str(Path(module.__file__).relative_to(ROOT).as_posix()),
            "driver_class": cls.__name__,
            "model_ids": list(cls.MODEL_IDS),
            "max_voltage_v": float(limits.max_voltage),
            "max_current_a": float(limits.max_current),
            "voltage_ranges_n": len(limits.voltage_ranges),
            "current_ranges_n": len(limits.current_ranges),
            "power_envelope_n": len(limits.power_envelope),
            "sweep_kind": getattr(cls, "SWEEP_KIND", "software"),
            "nplc_min": None if not nplc else float(nplc[0]),
            "nplc_max": None if not nplc else float(nplc[1]),
            "high_z_off": bool(getattr(cls, "HIGH_Z_OFF", False)),
            "ovp": bool(getattr(cls, "OVP_CHOICES", None)),
            "remote_sense_control": bool(getattr(cls, "REMOTE_SENSE_CONTROL", True)),
            # A driver that inherits BaseSMU's stub cannot report
            # compliance. Asked by identity rather than by name, because
            # a driver could define the method and still not implement
            # it - and "not reported" is the answer that matters at the
            # bench either way.
            "compliance_trip": (
                cls.compliance_tripped is not BaseSMU.compliance_tripped
            ),
        }
    return facts


# --------------------------------------------------------------------------
# Facts from git
# --------------------------------------------------------------------------

def repo_is_shallow() -> bool:
    """True when history is truncated, so per-file dates are unusable.

    `actions/checkout` clones with depth 1 by default, and on a shallow
    clone `git log -1 -- <path>` reports HEAD for every tracked file -
    which would mark the entire fleet stale for a reason that has
    nothing to do with the fleet. The CI workflow sets fetch-depth: 0;
    this is the guard for anyone who has not.
    """
    out = subprocess.run(
        ["git", "rev-parse", "--is-shallow-repository"],
        cwd=ROOT, text=True, capture_output=True,
    )
    return out.returncode != 0 or out.stdout.strip() == "true"


def last_changed(paths: list[str]) -> date | None:
    """Date of the most recent commit touching any of `paths`."""
    newest = None
    for rel in paths:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", rel],
            cwd=ROOT, text=True, capture_output=True,
        )
        stamp = out.stdout.strip()
        if out.returncode != 0 or not stamp:
            continue
        when = date.fromisoformat(stamp)
        if newest is None or when > newest:
            newest = when
    return newest


def bench_status(meta: dict) -> tuple[str, str]:
    """Derive (status, reason) for one driver. Never hand-written.

    Three states, and the middle one is the whole point:

    * `unverified` - this driver has never passed a checkup against its
      instrument. The 2450 is here because the hardware belongs to
      another lab.
    * `stale` - it passed once, and has been modified since. The
      checkup's answers were about code that no longer exists.
    * `commissioned` - it passed, and nothing it depends on has moved.
    """
    if meta.get("bench_ever") is not True:
        return "unverified", "never run against its instrument"

    revalidated = meta.get("bench_revalidated")
    if revalidated:
        return "commissioned", f"revalidated by inspection: {revalidated}"

    when = meta.get("last_bench")
    if not when:
        return "stale", "passed a checkup, but the date was not recorded"

    if repo_is_shallow():
        return "unknown", "shallow clone - history unavailable"

    deps = [meta["driver"], *SHARED_DEPENDENCIES]
    moved = last_changed(deps)
    if moved is None:
        return "unknown", "no git history for this driver"
    if moved > date.fromisoformat(str(when)):
        return "stale", f"code changed {moved.isoformat()}, after the {when} checkup"
    return "commissioned", f"checked {when}, unchanged since"


# --------------------------------------------------------------------------
# Generators
# --------------------------------------------------------------------------

def instrument_notes() -> list[Path]:
    return sorted(INSTRUMENTS.glob("*.md"))


def load_notes(physical_only: bool = False) -> dict[Path, tuple[dict, str]]:
    """Every instrument note, or only the ones describing real hardware.

    `DummySMU` is a registered driver and must have a note - the
    bijection test insists, so demo mode cannot quietly diverge from the
    real drivers. But it is not an instrument: listing it in a chooser
    table aimed at the bench would offer a simulated SMU as a
    measurement option, and putting it in the checkup-owed list would
    demand a bench session for a thing that has no bench.
    """
    notes = {p: read_frontmatter(p) for p in instrument_notes()
             if not p.name.startswith("_")}
    if physical_only:
        notes = {p: v for p, v in notes.items() if v[0].get("physical") is not False}
    return notes


def sync_frontmatter(write: bool = True) -> list[str]:
    """Write the code-derived block into each instrument note.

    Returns the list of notes whose generated block was out of date.
    """
    facts = driver_facts()
    stale = []
    for path, (meta, body) in load_notes().items():
        cls = meta.get("driver_class")
        if cls not in facts:
            continue
        text = path.read_text(encoding="utf-8")
        rebuilt = _rebuild_generated_block(text, facts[cls])
        if rebuilt != text:
            stale.append(str(path.relative_to(ROOT).as_posix()))
            if write:
                path.write_text(rebuilt, encoding="utf-8")
    return stale


def _rebuild_generated_block(text: str, facts: dict) -> str:
    """Replace the generated span of a note's frontmatter, in place.

    Anchored on two markers and asserted to find both. A silent
    no-match that writes the file back unchanged is the exact failure
    this project has been bitten by before, so it raises instead.
    """
    lines = [f"{key}: {_dump_scalar(value)}" for key, value in facts.items()]
    block = "\n".join([GEN_BEGIN, *lines, GEN_END])

    start = text.find(GEN_BEGIN)
    end = text.find(GEN_END)
    if start == -1 or end == -1:
        raise FrontmatterError(
            "instrument note is missing the generated-block markers "
            f"({GEN_BEGIN!r} / {GEN_END!r})"
        )
    return text[:start] + block + text[end + len(GEN_END):]


def _preserved(path: Path) -> str:
    """The hand-written span of a generated file, if it already exists."""
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8")
    start, end = text.find(KEEP_BEGIN), text.find(KEEP_END)
    if start == -1 or end == -1:
        return ""
    return text[start + len(KEEP_BEGIN):end].strip("\n")


def _si(value: float, unit: str) -> str:
    for scale, prefix in ((1e-12, "p"), (1e-9, "n"), (1e-6, "u"),
                          (1e-3, "m"), (1.0, ""), (1e3, "k")):
        if abs(value) < scale * 1000:
            return f"{value / scale:g} {prefix}{unit}"
    return f"{value:g} {unit}"


def render_chooser() -> str:
    """The capability matrix, plus a preserved block of human guidance."""
    rows = []
    for path, (meta, _) in sorted(load_notes(physical_only=True).items()):
        status, _reason = bench_status(meta)
        mark = {"commissioned": "yes", "stale": "**re-check**",
                "unverified": "**never**", "unknown": "?"}[status]
        rows.append((
            meta.get("title") or path.stem.replace("-", " "),
            _si(meta["max_voltage_v"], "V"),
            _si(meta["max_current_a"], "A"),
            meta.get("reading_time") or "-",
            "hardware" if meta["sweep_kind"] == "hardware" else "software",
            "4-wire only" if not meta["remote_sense_control"] else "switchable",
            "yes" if meta["compliance_trip"] else "no",
            mark,
        ))

    head = ("| Instrument | Max V | Max I | Per reading | Sweep | Sensing "
            "| Reports compliance | Verified |")
    sep = "|---|---|---|---|---|---|---|---|"
    body = "\n".join("| " + " | ".join(r) + " |" for r in rows)

    return (
        f"{BANNER}\n"
        "# Choosing an SMU\n\n"
        "Every number below comes from the driver's own declarations, so "
        "this table cannot disagree with the software.\n\n"
        "**Read the Verified column first.** `re-check` means the driver "
        "has been modified since it was last run against the instrument: "
        "the measurement may be fine, but nobody has confirmed it. "
        "`never` means it has never met hardware at all. Run "
        "`uv run tools/smu_checkup.py --address <addr>` before trusting "
        "either.\n\n"
        f"{head}\n{sep}\n{body}\n\n"
        "Per-instrument detail, including what each one gets wrong, is in "
        "`bench/instruments/`.\n\n"
        "---\n\n"
        f"{KEEP_BEGIN}\n"
        "## Which instrument for which measurement\n\n"
        "*(Written by hand. Everything above is generated; this section is "
        "preserved across rebuilds.)*\n"
        f"{KEEP_END}\n"
    )


def render_checkup_owed() -> str:
    """Which drivers need a bench session, and why."""
    lines = []
    for path, (meta, _) in sorted(load_notes(physical_only=True).items()):
        status, reason = bench_status(meta)
        if status == "commissioned":
            continue
        lines.append(
            f"| {meta.get('title') or path.stem} | `{meta['driver']}` | "
            f"{status} | {reason} |"
        )

    body = "\n".join(lines) if lines else "| - | - | - | nothing owed |"
    return (
        f"{BANNER}\n"
        "# Checkup owed\n\n"
        "A driver is *commissioned* only while the code that was checked "
        "is the code that is running. Wave 6 modified every driver in the "
        "registry, which is why this list is longer than it looks like it "
        "should be.\n\n"
        "This is derived from git history against each note's "
        "`last_bench` date - nobody maintains it, and it cannot claim a "
        "driver is current when the file has moved.\n\n"
        "| Instrument | Driver | Status | Why |\n|---|---|---|---|\n"
        f"{body}\n\n"
        "Run `uv run tools/smu_checkup.py --address <addr> --trace`, then "
        "set `last_bench` in the instrument's note and rebuild.\n"
    )


DEVIATION_RE = re.compile(r"DEVIATION\s+(\d+)")


def render_deviation_index() -> str:
    """Every `# DEVIATION n` marker in the source, and where it sits.

    The prose ledger lives with each instrument and experiment. This is
    the lookup table for the other direction: given a number in a
    commit message or an old conversation, which file carries it.
    """
    found: dict[int, list[str]] = {}
    for path in sorted(ROOT.rglob("*.py")):
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith((".venv/", "build/", "dist/")):
            continue
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for match in DEVIATION_RE.finditer(line):
                found.setdefault(int(match.group(1)), []).append(f"`{rel}`:{n}")

    rows = "\n".join(
        f"| {number} | {', '.join(places)} |"
        for number, places in sorted(found.items())
    )
    return (
        f"{BANNER}\n"
        "# Deviation index\n\n"
        "Deviation numbers are permanent and global. They are cited from "
        "source comments, commit messages and past conversations, so they "
        "are never renumbered - only the note that explains them moves.\n\n"
        "This table lists the markers **in the code**. A deviation with no "
        "row here is documented but not marked at a call site, which is "
        "normal for the ones describing a whole driver.\n\n"
        "| Deviation | Marked at |\n|---|---|\n"
        f"{rows}\n"
    )


# --------------------------------------------------------------------------
# Bench-page extraction
#
# Not wired to any real content yet - the instrument notes are stubs
# until docs-instruments-v1. The function is here, and unit-tested
# against a fixture, so the mechanism is proven before it is adopted.
# Same shape as Wave 6d-i: build the capability, prove it in isolation,
# adopt it in the next patch.
# --------------------------------------------------------------------------

BENCH_MARKER = "<!-- bench -->"


def extract_bench_sections(body: str) -> str:
    """Return the `## ` sections of `body` marked for the bench pages.

    Extraction, deliberately, not summarisation. A generator that
    shortened would be making judgements about what a bench scientist
    needs to know, and the things most worth carrying across - the
    interlock is jumpered, this driver has never met hardware - are
    exactly the ones a shortener would drop as detail.
    """
    out: list[str] = []
    keeping = False
    for line in body.splitlines():
        if line.startswith("## "):
            keeping = BENCH_MARKER in line
            if keeping:
                out.append(line.replace(BENCH_MARKER, "").rstrip())
            continue
        if line.startswith("# "):
            keeping = False
            continue
        if keeping:
            out.append(line)
    return "\n".join(out).strip("\n")


# --------------------------------------------------------------------------

GENERATED = {
    BENCH / "choosing-an-smu.md": render_chooser,
    DOCS / "open" / "checkup-owed.md": render_checkup_owed,
    DOCS / "reference" / "deviation-index.md": render_deviation_index,
}


def build(check: bool = False) -> list[str]:
    """Write (or verify) every generated file. Returns what was stale."""
    stale = sync_frontmatter(write=not check)

    for path, render in GENERATED.items():
        keep = _preserved(path)
        text = render()
        if keep:
            start = text.find(KEEP_BEGIN) + len(KEEP_BEGIN)
            end = text.find(KEEP_END)
            text = text[:start] + "\n" + keep + "\n" + text[end:]
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(str(path.relative_to(ROOT).as_posix()))
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if any generated file is stale")
    args = parser.parse_args()

    stale = build(check=args.check)
    if args.check:
        if stale:
            print("Generated documentation is out of date:")
            for name in stale:
                print(f"  {name}")
            print("\nRun: uv run python tools/build_docs.py")
            return 1
        print("Generated documentation is up to date.")
        return 0

    if stale:
        print("Rewrote:")
        for name in stale:
            print(f"  {name}")
    else:
        print("Nothing to do.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
